// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAnX3BA6VTppFHXNJosbLK_gRyWW3PZaw',
    appId: '1:1072334388749:web:1d568988c632ef68c45f44',
    messagingSenderId: '1072334388749',
    projectId: 'customcraftapp',
    authDomain: 'customcraftapp.firebaseapp.com',
    storageBucket: 'customcraftapp.firebasestorage.app',
    measurementId: 'G-421PC9KBKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_omf_kp89Ojmoky7vcKIWHQXswF2DYHU',
    appId: '1:1072334388749:android:b1012b4a42d47266c45f44',
    messagingSenderId: '1072334388749',
    projectId: 'customcraftapp',
    storageBucket: 'customcraftapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdFpvPolTLcBeCTah1laUvsIhbsxAWi_Y',
    appId: '1:1072334388749:ios:c16b3d3255e60a12c45f44',
    messagingSenderId: '1072334388749',
    projectId: 'customcraftapp',
    storageBucket: 'customcraftapp.firebasestorage.app',
    iosClientId: '1072334388749-fenh2phq0eben5ndh8e1i89rjoo1p8bm.apps.googleusercontent.com',
    iosBundleId: 'com.jeopardyapps.customcraftapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdFpvPolTLcBeCTah1laUvsIhbsxAWi_Y',
    appId: '1:1072334388749:ios:c16b3d3255e60a12c45f44',
    messagingSenderId: '1072334388749',
    projectId: 'customcraftapp',
    storageBucket: 'customcraftapp.firebasestorage.app',
    iosClientId: '1072334388749-fenh2phq0eben5ndh8e1i89rjoo1p8bm.apps.googleusercontent.com',
    iosBundleId: 'com.jeopardyapps.customcraftapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAnX3BA6VTppFHXNJosbLK_gRyWW3PZaw',
    appId: '1:1072334388749:web:4cbffedc45b7f47ec45f44',
    messagingSenderId: '1072334388749',
    projectId: 'customcraftapp',
    authDomain: 'customcraftapp.firebaseapp.com',
    storageBucket: 'customcraftapp.firebasestorage.app',
    measurementId: 'G-PN83NQNDLH',
  );

}